### ISSUE TITLE
cryptography.fernet.InvalidToken

### ISSUE THREAD

**Issue by ronniemo** [cordon-thiago/airflow-spark#13]
I define the DB connection in pySpark. So no need for an Airflow-Connection. Why there is an error like the one below?

[2021-03-02 08:00:14,932] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: etl_sad_reporting.etl_customer_dialog 2021-03-02T07:58:57.850780+00:00 [running]> fee10b35f03f
[2021-03-02 08:00:14,966] {{taskinstance.py:1088}} ERROR - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/contrib/operators/spark_submit_operator.py", line 179, in execute
    spark_binary=self._spark_binary
  File "/usr/local/lib/python3.6/site-packages/airflow/contrib/hooks/spark_submit_hook.py", line 149, in __init__
    self._connection = self._resolve_connection()
  File "/usr/local/lib/python3.6/site-packages/airflow/contrib/hooks/spark_submit_hook.py", line 183, in _resolve_connection
    conn = self.get_connection(self._conn_id)
  File "/usr/local/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 84, in get_connection
    log.info("Using connection to: %s", conn.log_info())
  File "/usr/local/lib/python3.6/site-packages/airflow/models/connection.py", line 321, in log_info
    "XXXXXXXX" if self.extra_dejson else None))
  File "/usr/local/lib/python3.6/site-packages/airflow/models/connection.py", line 338, in extra_dejson
    if self.extra:
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 356, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.6/site-packages/airflow/models/connection.py", line 212, in get_extra
    return fernet.decrypt(bytes(self._extra, 'utf-8')).decode()
  File "/usr/local/lib/python3.6/site-packages/cryptography/fernet.py", line 194, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
[2021-03-02 08:00:14,969] {{taskinstance.py:1117}} INFO - All retries failed; marking task as FAILED
[2021-03-02 08:00:24,812] {{logging_mixin.py:112}} INFO - [2021-03-02 08:00:24,812] {{local_task_job.py:103}} INFO - Task exited with return code 1

**Comment by yansfil** [comment]
I have same error

**Comment by ronniemo** [comment]
@yansfil Check your connections in Airflow or restart the Airflow image.
